---
- hosts: mysql_linux
  tasks:
  - name: Update du systeme
    become: true
    become_user: root
    apt:
      update_cache: yes

  tasks:
  - name: Installation gnupg
    become: true
    become_user: root
    apt:
      name: gnupg
      state: latest

  tasks:
  - name: installation du dernier paquet mysql 8
    become: true
    become_user: root
    apt:
      deb: https://dev.mysql.com/get/mysql-apt-config_0.8.16-1_all.deb

  tasks:
  - name: Installation de mysql 8 serveur
    become: true
    become_user: root
    apt:
      name: mysql-server 
      state: latest

  tasks:
  - name: Installation de mysql 8 client
    become: true
    become_user: root
    apt:
      name: mysql-client 
      state: latest

  tasks:
  - name: Stop service MySQL
    become: true
    become_user: root
    shell: "sudo /etc/init.d/mysql stop"

  tasks:
  - name: Creation dossier debug
    become: true
    become_user: root
    file:
      path: /var/run/mysqld
      state: directory
      owner: mysql

  tasks:
  - name: Lancement debug mysql
    become: true
    become_user: root
    shell: "sudo mysqld_safe --skip-grant-tables&"

  <!-- Se playbook nécéssite le module Ansible community.mysql --!>

  tasks:
  - name: Suppression mode de passe utilisateur root dans MySQL
    become: true
    become_user: root
    community.mysql.mysql_query:
      login_db: root
      query: UPDATE mysql.user SET authentication_string=null WHERE User='root';

  tasks:
  - name: Flush des privilèges
    become: true
    become_user: root
    community.mysql.mysql_query:
      login_db: root
      query: FLUSH PRIVILEGES;

  tasks:
  - name: Arret du debug
    become: true
    become_user: root
    shell: "sudo killall -u mysql"

  tasks:
  - name: Demarrage de MySQL
    become: true
    become_user: root
    shell: "sudo /etc/init.d/mysql start"

  <!-- Il n'y aura plus de mot de passe sur le compte root, il faudra en rajouter un manuellement --!>