---
- hosts: mysql_linux
  tasks:
  - name: Update du systeme
    become: true
    become_user: root
    apt:
      update_cache: yes

  tasks:
  - name: Installation gnupg
    become: true
    become_user: root
    apt:
      name: gnupg
      state: latest

  tasks:
  - name: installation du dernier paquet mysql 8
    become: true
    become_user: root
    apt:
      deb: https://dev.mysql.com/get/mysql-apt-config_0.8.16-1_all.deb

  tasks:
  - name: Installation de mysql 8 serveur
    become: true
    become_user: root
    apt:
      name: mysql-server 
      state: latest

  tasks:
  - name: Installation de mysql 8 client
    become: true
    become_user: root
    apt:
      name: mysql-client 
      state: latest